### ISSUE TITLE
не получается запусить скрипт

### ISSUE THREAD

**Issue by roggi** [vscoder/loopdetect#1]
Привет! не поможешь запустить скрипт, вроде поставил все зависимости, но все ругается

roggi@len ~ $ sudo ./loop.py 
[sudo] password for roggi: 
Send packet to eth0
Traceback (most recent call last):
  File "./loop.py", line 105, in <module>
    main()
  File "./loop.py", line 102, in main
    ld.Process()
  File "./loop.py", line 54, in Process
    hw = dnet.eth(self.iface)
AttributeError: 'module' object has no attribute 'eth'

**Comment by vscoder** [comment]
Попробуй запустить 
sudo ./loopdetect.py list
И напиши что он выдаст

**Comment by roggi** [comment]
roggi@len ~ $ sudo ./loop.py list
[sudo] password for roggi:
Index: 0 Device name: eth0
Index: 1 Device name: wlan0
Index: 2 Device name: ppp0
Index: 3 Device name: bluetooth0
Index: 4 Device name: nflog
Index: 5 Device name: nfqueue
Index: 6 Device name: any
Index: 7 Device name: lo

04.01.2015 10:58, vscoder пишет:

**Comment by vscoder** [comment]
Что за устройство, ноутбук? Версия ОС? На каком интерфейсе необходим поиск петли?

**Comment by roggi** [comment]
ноутбук, mint 17. на eth0.
так же пробовал на простом компе, который в качестве роутера на одной из 
сетей используется, такая же ошибка. такое ощущение что какой то из 
пакетов не так поставил.

05.01.2015 00:49, vscoder пишет:
